### ISSUE TITLE
Add serviceNow Logo icon to Marketplace listing

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-app-servicenow#28]
This is the SVG icon we can use: https://symbols.getvecta.com/stencil_95/72_servicenow.d5b0a698d4.svg

**Comment by hanzei** [comment]
Right now there is no way to attach an icon to an App in the Marketplace. https://mattermost.atlassian.net/browse/MM-34921 will add that.

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-app-servicenow/pull/37
